// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hybrid.Repositories.Models;

public partial class Course
{
    public string CourseId { get; set; }

    public string CourseName { get; set; }

    public string DataText { get; set; }

    public string LevelId { get; set; }

    public virtual Level Level { get; set; }

    public virtual ICollection<Minigame> Minigames { get; set; } = new List<Minigame>();
}