// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hybrid.Repositories.Models;

public partial class Level
{
    public string LevelId { get; set; }

    public string LevelName { get; set; }

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}