// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hybrid.Repositories.Models;

public partial class MinigameTemplate
{
    public string TemplateId { get; set; }

    public string TemplateName { get; set; }

    public string Image { get; set; }

    public string Summary { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Minigame> Minigames { get; set; } = new List<Minigame>();
}