// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hybrid.Repositories.Models;

public partial class Minigame
{
    public string MinigameId { get; set; }

    public string MinigameName { get; set; }

    public string TeacherId { get; set; }

    public string ThumbnailIimage { get; set; }

    public string DataText { get; set; }

    public int Duration { get; set; }

    public int? ParticipantsCount { get; set; }

    public double? RatingScore { get; set; }

    public string TemplateId { get; set; }

    public string CourseId { get; set; }

    public virtual Course Course { get; set; }

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual ICollection<StudentAccomplisment> StudentAccomplisments { get; set; } = new List<StudentAccomplisment>();

    public virtual Teacher Teacher { get; set; }

    public virtual MinigameTemplate Template { get; set; }
}