// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hybrid.Repositories.Models;

public partial class Student
{
    public string UserId { get; set; }

    public string FullName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public int YearOfBirth { get; set; }

    public string TierId { get; set; }

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual ICollection<StudentAccomplisment> StudentAccomplisments { get; set; } = new List<StudentAccomplisment>();

    public virtual ICollection<StudentSupscription> StudentSupscriptions { get; set; } = new List<StudentSupscription>();

    public virtual StudentTier Tier { get; set; }

    public virtual User User { get; set; }
}