// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hybrid.Repositories.Models;

public partial class StudentTier
{
    public string TierId { get; set; }

    public string TierName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<StudentSupscription> StudentSupscriptions { get; set; } = new List<StudentSupscription>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}