// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hybrid.Repositories.Models;

public partial class StudentSupscription
{
    public string StudentId { get; set; }

    public string TierId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool IsActive { get; set; }

    public virtual Student Student { get; set; }
    public virtual ICollection<SupscriptionExtentionOrder> SupscriptionExtentionOrders { get; set; } = new List<SupscriptionExtentionOrder>();
    public virtual StudentTier Tier { get; set; }
}