// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hybrid.Repositories.Models;

public partial class StudentAccomplisment
{
    public string StudentId { get; set; }

    public string MinigameId { get; set; }

    public double Score { get; set; }

    public int Duration { get; set; }

    public DateTime TakenDate { get; set; }

    public virtual Minigame Minigame { get; set; }

    public virtual Student Student { get; set; }
}