// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hybrid.Repositories.Models;

public partial class SupscriptionExtentionOrder
{
    public string UserId { get; set; }

    public string TierId { get; set; }

    public string TransactionId { get; set; }

    public int Days { get; set; }

    public virtual StudentSupscription StudentSupscription { get; set; }

    public virtual TeacherSupscription TeacherSupscription { get; set; }

    public virtual TransactionHistory Transaction { get; set; }
}