// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hybrid.Repositories.Models;

public partial class TeacherSupscription
{
    public string TeacherId { get; set; }

    public string TierId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public bool IsActive { get; set; }

    public virtual Teacher Teacher { get; set; }

    public virtual TeacherTier Tier { get; set; }
}