// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hybrid.Repositories.Models;

public partial class Teacher
{
    public string UserId { get; set; }

    public string FullName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public int YearOfBirth { get; set; }

    public string TierId { get; set; }

    public virtual ICollection<Minigame> Minigames { get; set; } = new List<Minigame>();

    public virtual ICollection<TeacherSupscription> TeacherSupscriptions { get; set; } = new List<TeacherSupscription>();

    public virtual TeacherTier Tier { get; set; }

    public virtual User User { get; set; }
}