// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hybrid.Repositories.Models;

public partial class TransactionHistory
{
    public string TransactionId { get; set; }

    public double Amount { get; set; }

    public string MethodId { get; set; }

    public int Status { get; set; }

    public virtual PaymentMethod Method { get; set; }

    public virtual ICollection<SupscriptionExtentionOrder> SupscriptionExtentionOrders { get; set; } = new List<SupscriptionExtentionOrder>();
}