// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hybrid.Repositories.Models;

public partial class User
{
    public string UserId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public DateTime CreatedDate { get; set; }

    public string RoleId { get; set; }

    public string ResetCode { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiryTime { get; set; }

    public bool IsActive { get; set; }

    public virtual Role Role { get; set; }

    public virtual Student Student { get; set; }

    public virtual Teacher Teacher { get; set; }
}